ENCODER:
  IN_CHANNEL_LIST:    [3,    16,   32,   48,   64,   80,   96,   112,  128,  144,  160,  176]
  OUT_CHANNEL_LIST:   [16,   32,   48,   64,   80,   96,   112,  128,  144,  160,  176,  192]
  NORMALIZATION_LIST: [true, true, true, true, true, true, true, true, true, true, true, false]
  KERNEL_SIZE_LIST:   [1,    3,    3,    1,    3,    3,    1,    3,    3,    1,    3,    3]
  STRIDE_LIST:        [1,    1,    2,    1,    1,    2,    1,    1,    2,    1,    1,    2]
  PADDING_LIST:       [0,    1,    1,    0,    1,    1,    0,    1,    1,    0,    1,    1]
DECODER:
  IN_CHANNEL_LIST:    [192,  176,  160,  144,  128,  96,   64,   32]
  OUT_CHANNEL_LIST:   [176,  160,  144,  128,  96,   64,   32,   3]
  KERNEL_SIZE_LIST:   [2,    3,    2,    3,    2,    3,    2,    3]
  STRIDE_LIST:        [2,    1,    2,    1,    2,    1,    2,    1]
  PADDING_LIST:       [0,    1,    0,    1,    0,    1,    0,    1]

