ENCODER:
  IN_CHANNEL_LIST:    [3,    64,   64,   128,  256,  256,  512,  128,  128,  32]
  OUT_CHANNEL_LIST:   [64,   64,   128,  256,  256,  512,  128,  128,  32,   8]
  NORMALIZATION_LIST: [true, true, true, true, true, true, true, true, true, false]
  KERNEL_SIZE_LIST:   [1,    3,    3,    1,    3,    3,    1,    3,    3,    3]
  STRIDE_LIST:        [1,    1,    2,    1,    1,    2,    1,    1,    2,    1]
  PADDING_LIST:       [0,    1,    1,    0,    1,    1,    0,    1,    1,    1]
DECODER:
  IN_CHANNEL_LIST:    [8,    64,   256,  128,  64,   32]
  OUT_CHANNEL_LIST:   [64,   256,  128,  64,   32,   3]
  KERNEL_SIZE_LIST:   [2,    3,    2,    3,    2,    3]
  STRIDE_LIST:        [2,    1,    2,    1,    2,    1]
  PADDING_LIST:       [0,    1,    0,    1,    0,    1]